<?php

namespace AppBundle\Repository;

/**
 * CarLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
