<?php

namespace AppBundle\Repository;

/**
 * RoutePointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutePointRepository extends \Doctrine\ORM\EntityRepository
{
}
